package com.example.testrecyclerwithstate

class ModelWithState(val index: Int, val text: String, var isSelected: Boolean) {




    // autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as ModelWithState

        if (text != other.text) return false
        if (isSelected != other.isSelected) return false

        return true
    }

    // autogenerated
    override fun hashCode(): Int {
        var result = text.hashCode()
        result = 31 * result + isSelected.hashCode()
        return result
    }

    //autogenerated
    override fun toString(): String {
        return "ModelWithState(text='$text', isSelected=$isSelected)"
    }
}